spring.application.name=priority-task-scheduler
#?????? DeepSeek API Key
spring.ai.openai.api-key="sk-0928cd2adcf34a26a37b55b406e6b511"

# ??????? DeepSeek ???????? OpenAI
spring.ai.openai.base-url=https://api.deepseek.com/chat/completions

# ???? DeepSeek ?????
spring.ai.openai.chat.options.model=deepseek-chat